version: "3"
services:
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db