version: "3"
services:
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myBooks
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - ./data-volume:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    expose: 
      - "3306"
    networks:
      - app-db
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-db

networks:
  app-db:

volumes:
  data_volume: